sudo: required
services:
  - docker

before_install:
  - docker build -t akinsanya4/docker-react -f Dockerfile.dev .

script:
  - docker run akinsanya4/docker-react npm run test test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-561498469643"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: ""$AWS_SECRET_KEY"


install: travis_wait 30
